name: cd

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.GCP_ARTIFACT_REPO }}/scraping-service:${{ github.sha }}

  deploy:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: live
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image=${{ secrets.GCP_ARTIFACT_REPO }}/scraping-service:${{ github.sha }} \
          --allow-unauthenticated --region=${{ secrets.GCP_REGION }} --port=6003 \
          --set-env-vars="SCRAPING_SERVICE_KEY=${{ secrets.SCRAPING_SERVICE_KEY }}"
